version: '3.3'

services:
  greenshop-api:
    container_name: greenshop-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3003
    volumes:
      - ./:/usr/src/greenshop
    working_dir: /usr/src/greenshop

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  greenshop-batch:
    container_name: greenshop-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3004
    volumes:
      - ./:/usr/src/greenshop
    working_dir: /usr/src/greenshop

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# greenhouse-next: localhost:4000 <=> container:3000
# greenhouse-api: localhost:4001 <=> container:3007
# greenhouse-batch: localhost:4002 <=> container:3008
